<?php
/**
 * implementation of hook_menu
 */
function ncp_menu(){
  $items = array();
  $items['admin/config/system/ncp'] = array(
    'title' => '内容分页设置',
    'description' => '内容分页设置',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ncp_admin_settings'),
    'access arguments' => array('ncp_admin_settings'),
    'file' => 'ncp.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * implementation of hook_permission
 */
function ncp_permission(){
  return array(
    'ncp_admin_settings' => array(
      'title' => t('配置内容分页'),
      'description' =>t('配置内容分页'), 
    ),
  );
}

/**
 * implementation of hook_node_view
 * @param $node
 * @param $view_mode
 * @param $langcode
 */
function ncp_node_view($node, $view_mode, $langcode){
  module_load_include('inc', 'ncp', 'ncp.class.pager');
  $accessnc = array_keys(array_filter(variable_get('ncp_type')));
  if(in_array($node->type, $accessnc) && arg(0)=='node' && is_numeric(arg(1))){
    $content = (isset($node->content['body'][0]['#markup'])) ? $node->content['body'][0]['#markup'] : '';
    $contentarr = explode('_baidu_page_break_tag_', $content);
    $ncppager = new Pager(count($contentarr),1,'pager-item');
    if($ncppager->pg){
      $node->content['body'][0]['#markup'] = $contentarr[$ncppager->pg-1];
      $node->content['bodypager'][0]['#markup'] = '<div class="item-list"><ul class="pager">'.$ncppager->thestr.'</ul></div>';
    }  
  }
}    
